spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    password: postgres
    username: postgres
  application:
    name: pagamentos-ms
server:
  port: 0
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.int}
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka
resilience4j:
  circuitbreaker:
    instances:
      atualizaPedido:
        sliding-window-size: 3
        minimum-number-of-calls: 2
        wait-duration-in-open-state: 50s